version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: ets-postgres
    restart: always
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticketing"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ets-network

  redis:
    image: redis:7
    container_name: ets-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ets-network

volumes:
  postgres_data:

networks:
  ets-network:
    driver: bridge
